# Generated by Django 4.0.4 on 2022-04-15 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixel_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pixels',
            name='x_axis',
        ),
    ]
