# Generated by Django 4.0.4 on 2022-04-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel_app', '0002_remove_pixels_x_axis'),
    ]

    operations = [
        migrations.AddField(
            model_name='pixels',
            name='color',
            field=models.CharField(default='white', max_length=100),
        ),
        migrations.AddField(
            model_name='pixels',
            name='x_axis',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='pixels',
            name='y_axis',
            field=models.IntegerField(default=None),
        ),
    ]
