# Generated by Django 4.0.4 on 2022-04-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel_app', '0004_owner_pixels_current_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='owner_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
