# Generated by Django 4.0.4 on 2022-04-16 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixel_app', '0005_owner_owner_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pixels',
            new_name='Pixel',
        ),
    ]
