# Generated by Django 4.0.4 on 2022-04-16 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pixel_app', '0006_rename_pixels_pixel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(default=None, max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='pixel',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='color', to='pixel_app.color'),
        ),
    ]
