# Generated by Django 4.0.4 on 2022-04-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel_app', '0007_color_alter_pixel_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color_name',
            field=models.CharField(default='white', max_length=30),
        ),
    ]
