# Generated by Django 4.0.4 on 2022-04-16 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixel_app', '0009_alter_color_color_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pixel',
            old_name='color',
            new_name='colors',
        ),
    ]
