# Generated by Django 4.0.4 on 2022-04-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel_app', '0010_rename_color_pixel_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='pixel',
            name='color',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
