# Generated by Django 4.0.4 on 2022-04-19 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pixel_app', '0011_pixel_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pixel',
            name='color',
        ),
        migrations.AlterField(
            model_name='pixel',
            name='colors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='color', to='pixel_app.color'),
        ),
    ]
