# Generated by Django 4.0.4 on 2022-04-19 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixel_app', '0012_remove_pixel_color_alter_pixel_colors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pixel',
            old_name='colors',
            new_name='color',
        ),
    ]
