# Generated by Django 4.0.4 on 2022-04-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel_app', '0013_rename_colors_pixel_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='pixel',
            name='number_of_times_changed',
            field=models.IntegerField(default=None),
        ),
    ]
