# Generated by Django 4.0.4 on 2022-04-20 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pixel_app', '0015_comment_community_thread_alter_pixel_current_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='reply_thread',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comment', to='pixel_app.comment'),
        ),
    ]
