# Generated by Django 4.0.4 on 2022-04-21 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pixel_app', '0017_comment_creator_of_comment_community_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community', to=settings.AUTH_USER_MODEL),
        ),
    ]
