# Generated by Django 4.0.4 on 2022-04-21 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixel_app', '0018_alter_community_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='creator',
        ),
    ]
