# Generated by Django 4.0.4 on 2022-04-21 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel_app', '0021_alter_thread_reply_thread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='reply_thread',
        ),
        migrations.AddField(
            model_name='thread',
            name='reply_thread',
            field=models.ManyToManyField(null=True, related_name='comment', to='pixel_app.comment'),
        ),
    ]
