# Generated by Django 4.0.4 on 2022-04-21 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pixel_app', '0022_remove_thread_reply_thread_thread_reply_thread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='reply_thread',
        ),
        migrations.AddField(
            model_name='thread',
            name='reply_thread',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='pixel_app.comment'),
        ),
    ]
